import React from 'react';
import Head from 'next/head'
import { makeStyles } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import Container from '@material-ui/core/Container';
import Header from '@/modules/Header';
import Footer from '@/elements/Footer';
import Tabs from '@material-ui/core/Tabs';
import Tab from '@material-ui/core/Tab';
import Typography from '@material-ui/core/Typography';
import { useTabStyles, AntTab, AntTabs } from '@/styles/useTabStyles';

export default function Page(props) {
    const { title, children } = props;
    const sections = [
        //{ title: 'profile', url: '/integrator/profile' },
        //{ title: 'request', url: '/integrator/request' },
        //{ title: 'schedule', url: '/integrator/schedule' },
        //{ title: 'directory', url: '/integrator/directory' },
        //{ title: 'about', url: '/integrator/about' }
        //,{ title: 'home', url: '/home' }
    ]
    const info = {
        email: '',
        role: ''
    }

    return (
        <>
            <CssBaseline />
            <Head>
                <title>Radfx</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container maxWidth="lg">
                <Header title="RADFX" sections = {sections} info={info}/>
                <main>{children}</main>
            </Container>
            <Footer/>
        </>
    )
}